# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UHsrYUozyEHTJneFFkxzli-G2Z8Oy4ZJ
"""

import pandas as pd

def load_data(filepath, skiprows=57, nrows=5):
    """
    Load data from an Excel file with optional row skipping and limiting the number of rows.
    """
    df = pd.read_excel(filepath, skiprows=skiprows, nrows=nrows)
    return df

def clean_data(df, columns_to_drop, drop_na=True):
    """
    Clean data by replacing NaN and removing unwanted columns.
    Optionally drops columns with NaN values.
    """
    # Replace NaN with pd.NA
    df.replace(["", "NaN", None], pd.NA, inplace=True)

    # Drop specified columns
    df_cleaned = df.drop(df.columns[columns_to_drop], axis=1)

    # Drop NaN columns if specified
    if drop_na:
        df_cleaned = df_cleaned.dropna(axis=1, how='any')

    return df_cleaned

def rename_columns(df, new_columns):
    """
    Rename columns to give more meaningful names.
    """
    df.columns = new_columns
    return df

def merge_data(df1, df2, on_columns=['Order', 'Income']):
    """
    Merge two dataframes on specified columns.
    """
    return pd.merge(df1, df2, on=on_columns, how='inner')

def reshape_data(df):
    """
    Reshape the dataframe from wide to long format using pd.melt().
    """
    return pd.melt(df, id_vars=['Order', 'Income'], var_name='Category', value_name='Value')

def save_to_csv(df, filepath):
    """
    Save the cleaned and processed dataframe to a CSV file.
    """
    df.to_csv(filepath, index=False)
